# Description: Telemetry Configuration
---
version: 1
connection:
  id: duckdb_0
  driver: org.duckdb.DuckDBDriver
  url: jdbc:duckdb:${HOME}/local_benchmarks/lst-bench/results/fast_test_iceberg.duckdb
execute_ddl: true
ddl_file: ${LST_BENCH_HOME}/src/main/resources/scripts/logging/duckdb/ddl.sql
insert_file: ${LST_BENCH_HOME}/src/main/resources/scripts/logging/duckdb/insert.sql
# The following parameter values will be used to replace the variables in the logging statements.
parameter_values:
  data_path: ''